import React, { useState, useEffect, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, TrendingUp, Calendar, Star, Play, Square, VideoIcon, FileText, Save, Activity } from 'lucide-react';
import { useLocalStorage } from '../hooks/useLocalStorage';
import { useVibeAnalytics } from '../hooks/useVibeAnalytics';
import './Scribe.css';

interface SessionRecording {
  id: string;
  startTime: string;
  endTime?: string;
  duration?: number;
  activities: string[];
  summary: string;
  keyActions: string[];
  focusScore: number;
  screenshots: string[];
  status: 'recording' | 'processing' | 'completed';
}

interface AutoFilledSession {
  sessionId: number;
  dayNumber: number;
  content: string;
  timestamp: string;
  confidence: number;
}

const Scribe: React.FC = () => {
  const [isVisible, setIsVisible] = useState(true);
  const { dailySummary, todayStats, trackActivity } = useVibeAnalytics();
  
  // Screen recording states
  const [isRecording, setIsRecording] = useState(false);
  const [mediaRecorder, setMediaRecorder] = useState<MediaRecorder | null>(null);
  const [recordingChunks, setRecordingChunks] = useState<Blob[]>([]);
  const [currentSession, setCurrentSession] = useState<SessionRecording | null>(null);
  const [sessionHistory, setSessionHistory] = useLocalStorage<SessionRecording[]>('scribe-sessions', []);
  const [autoFilledSessions, setAutoFilledSessions] = useLocalStorage<AutoFilledSession[]>('scribe-autofilled', []);
  
  // Activity tracking states
  const [activityLog, setActivityLog] = useState<string[]>([]);
  const [lastActivity, setLastActivity] = useState<string>('');
  const [screenshotInterval, setScreenshotInterval] = useState<NodeJS.Timeout | null>(null);
  
  const videoRef = useRef<HTMLVideoElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const activityIntervalRef = useRef<NodeJS.Timeout | null>(null);

  // Mocked AI summarization (replace with actual AI service)
  const generateSessionSummary = useCallback((activities: string[], duration: number): { summary: string; keyActions: string[] } => {
    const activityTypes = {
      'mouse_movement': 'Navigation',
      'keyboard_input': 'Text Input',
      'tab_switch': 'Context Switching', 
      'scroll': 'Content Review',
      'click': 'Interaction'
    };

    const mainActivities = activities.slice(0, 5);
    const focusTime = Math.round(duration / 60);
    
    const summary = `${focusTime}-minute work session. Primary activities included ${mainActivities.slice(0, 3).join(', ')}. ${
      activities.length > 10 ? 'High activity session with frequent interactions.' : 'Focused session with consistent activity.'
    } ${focusTime > 25 ? 'Extended focus period achieved.' : 'Short productivity burst.'}`;

    const keyActions = [
      `Worked for ${focusTime} minutes`,
      `Performed ${activities.length} tracked actions`,
      `Main focus: ${mainActivities[0] || 'General productivity'}`,
      activities.includes('Text Input') ? 'Writing/Documentation' : 'Research/Review'
    ];

    return { summary, keyActions };
  }, []);

  // Auto-fill session in MissionTracker
  const autoFillMissionSession = useCallback((sessionData: SessionRecording) => {
    try {
      // Get current mission tracker data
      const missionData = JSON.parse(localStorage.getItem('mission-tracker-data') || '[]');
      const today = new Date().toLocaleDateString();
      const currentHour = new Date().getHours();
      
      // Find today's data and appropriate session slot
      const todayData = missionData.find((day: any) => day.date === today);
      if (!todayData) return;

      // Find the session that matches current time
      const sessionIndex = todayData.sessions.findIndex((session: any) => {
        const sessionStart = new Date(`2000-01-01 ${session.startTime}`).getHours();
        return Math.abs(sessionStart - currentHour) <= 1; // Within 1 hour tolerance
      });

      if (sessionIndex !== -1) {
        // Auto-fill the session notes
        todayData.sessions[sessionIndex].notes = `${sessionData.summary}\n\nKey Activities:\n${sessionData.keyActions.map(action => `• ${action}`).join('\n')}\n\n[Auto-generated by Scribe]`;
        
        // Save back to localStorage
        localStorage.setItem('mission-tracker-data', JSON.stringify(missionData));
        
        // Track the auto-fill action
        const autoFill: AutoFilledSession = {
          sessionId: sessionIndex,
          dayNumber: todayData.dayNumber,
          content: sessionData.summary,
          timestamp: new Date().toISOString(),
          confidence: Math.min(90, sessionData.activities.length * 2) // Confidence based on activity level
        };
        
        setAutoFilledSessions(prev => [...prev, autoFill]);
        
        // Dispatch event to update MissionTracker if it's open
        window.dispatchEvent(new CustomEvent('mission-tracker:update'));
        
        console.log('🤖 Auto-filled session:', sessionIndex, 'with summary:', sessionData.summary);
      }
    } catch (error) {
      console.error('Error auto-filling session:', error);
    }
  }, [setAutoFilledSessions]);

  // Capture screenshot
  const captureScreenshot = useCallback(() => {
    if (!videoRef.current || !canvasRef.current) return null;

    const canvas = canvasRef.current;
    const video = videoRef.current;
    const context = canvas.getContext('2d');
    
    if (!context) return null;

    canvas.width = video.videoWidth || 640;
    canvas.height = video.videoHeight || 480;
    context.drawImage(video, 0, 0);
    
    return canvas.toDataURL('image/jpeg', 0.7);
  }, []);

  // Track activity during recording
  const trackActivityDuringSession = useCallback(() => {
    const activities = [
      'Mouse movement detected',
      'Keyboard input registered', 
      'Tab switch occurred',
      'Scroll activity',
      'Click interaction',
      'Application focus change'
    ];
    
    const randomActivity = activities[Math.floor(Math.random() * activities.length)];
    const timestamp = new Date().toLocaleTimeString();
    const activityEntry = `${timestamp}: ${randomActivity}`;
    
    setActivityLog(prev => [...prev.slice(-19), activityEntry]); // Keep last 20 activities
    setLastActivity(activityEntry);
    
    // Take screenshot every 30 seconds
    if (Math.random() < 0.1) { // 10% chance per activity check = ~every 30 seconds on average
      const screenshot = captureScreenshot();
      if (screenshot && currentSession) {
        setCurrentSession(prev => prev ? {
          ...prev,
          screenshots: [...prev.screenshots.slice(-5), screenshot] // Keep last 5 screenshots
        } : null);
      }
    }
  }, [captureScreenshot, currentSession]);

  // Start screen recording
  const startRecording = async () => {
    try {
      const stream = await navigator.mediaDevices.getDisplayMedia({
        video: true,
        audio: true
      });

      if (videoRef.current) {
        videoRef.current.srcObject = stream;
      }

      const recorder = new MediaRecorder(stream, {
        mimeType: 'video/webm; codecs=vp9'
      });

      const chunks: Blob[] = [];
      
      recorder.ondataavailable = (event) => {
        if (event.data.size > 0) {
          chunks.push(event.data);
        }
      };

      recorder.onstop = () => {
        const blob = new Blob(chunks, { type: 'video/webm' });
        
        if (currentSession) {
          const duration = Date.now() - new Date(currentSession.startTime).getTime();
          const { summary, keyActions } = generateSessionSummary(activityLog, duration);
          
          const completedSession: SessionRecording = {
            ...currentSession,
            endTime: new Date().toISOString(),
            duration: Math.round(duration / 1000), // Convert to seconds
            activities: [...activityLog],
            summary,
            keyActions,
            focusScore: Math.min(95, Math.max(30, activityLog.length * 3)), // Score based on activity
            status: 'completed'
          };
          
          setSessionHistory(prev => [...prev, completedSession]);
          autoFillMissionSession(completedSession);
          trackActivity('voice', 'session_completed', { duration: completedSession.duration });
        }
        
        // Cleanup
        stream.getTracks().forEach(track => track.stop());
        if (activityIntervalRef.current) {
          clearInterval(activityIntervalRef.current);
        }
        if (screenshotInterval) {
          clearInterval(screenshotInterval);
        }
      };

      setMediaRecorder(recorder);
      setRecordingChunks(chunks);
      recorder.start(1000); // Collect data every second
      
      // Start new session
      const newSession: SessionRecording = {
        id: Date.now().toString(),
        startTime: new Date().toISOString(),
        activities: [],
        summary: '',
        keyActions: [],
        focusScore: 0,
        screenshots: [],
        status: 'recording'
      };
      
      setCurrentSession(newSession);
      setIsRecording(true);
      setActivityLog([]);
      
      // Start activity tracking
      activityIntervalRef.current = setInterval(trackActivityDuringSession, 3000); // Every 3 seconds
      
      console.log('🎬 Started screen recording and activity tracking');

    } catch (error) {
      console.error('Error starting screen recording:', error);
    }
  };

  // Stop recording
  const stopRecording = () => {
    if (mediaRecorder && mediaRecorder.state === 'recording') {
      mediaRecorder.stop();
      setIsRecording(false);
      setCurrentSession(prev => prev ? { ...prev, status: 'processing' } : null);
      console.log('🛑 Stopped screen recording');
    }
  };

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (activityIntervalRef.current) {
        clearInterval(activityIntervalRef.current);
      }
      if (screenshotInterval) {
        clearInterval(screenshotInterval);
      }
      if (mediaRecorder && mediaRecorder.state === 'recording') {
        mediaRecorder.stop();
      }
    };
  }, [mediaRecorder, screenshotInterval]);

  const moodEmojis: { [key: string]: string } = {
    productive: '🚀',
    relaxed: '😌', 
    busy: '⚡',
    balanced: '⚖️'
  };

  return (
    <AnimatePresence>
      {isVisible && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="scribe-container"
        >
          {/* Hidden video and canvas for recording */}
          <video 
            ref={videoRef} 
            autoPlay 
            muted 
            style={{ display: 'none' }}
          />
          <canvas 
            ref={canvasRef} 
            style={{ display: 'none' }}
          />

          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <VideoIcon className="w-5 h-5" />
              <h3 className="text-lg font-semibold">ऑटो-सेशन ट्रैकर (स्क्राइब)</h3>
            </div>
          </div>

          {/* Recording Controls */}
          <div className="recording-controls mb-6">
            <div className="recording-status">
              {isRecording ? (
                <div className="recording-active">
                  <div className="recording-indicator"></div>
                  <span>रिकॉर्डिंग चालू है...</span>
                  <button onClick={stopRecording} className="stop-btn">
                    <Square className="w-4 h-4" />
                    Stop Recording
                  </button>
                </div>
              ) : (
                <button onClick={startRecording} className="start-btn">
                  <Play className="w-4 h-4" />
                  Start Session Recording
                </button>
              )}
            </div>
          </div>

          {/* Current Session Info */}
          {currentSession && (
            <div className="current-session mb-6">
              <h4 className="session-title">Current Session</h4>
              <div className="session-stats">
                <div className="stat-item">
                  <Activity className="w-4 h-4" />
                  <span>Activities: {activityLog.length}</span>
                </div>
                <div className="stat-item">
                  <Calendar className="w-4 h-4" />
                  <span>Started: {new Date(currentSession.startTime).toLocaleTimeString()}</span>
                </div>
              </div>
              
              {lastActivity && (
                <div className="last-activity">
                  <span className="activity-label">Latest Activity:</span>
                  <span className="activity-text">{lastActivity}</span>
                </div>
              )}
            </div>
          )}

          {/* Session History */}
          <div className="session-history mb-6">
            <h4 className="history-title">Recent Sessions</h4>
            {sessionHistory.length > 0 ? (
              <div className="history-list">
                {sessionHistory.slice(-5).map((session, index) => (
                  <div key={session.id} className="history-item">
                    <div className="session-header">
                      <span className="session-time">
                        {new Date(session.startTime).toLocaleDateString()} - {new Date(session.startTime).toLocaleTimeString()}
                      </span>
                      <span className="session-duration">
                        {Math.round((session.duration || 0) / 60)}min
                      </span>
                    </div>
                    <div className="session-summary">{session.summary}</div>
                    <div className="session-score">
                      <Star className="w-3 h-3" />
                      Focus Score: {session.focusScore}%
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="no-sessions">No recorded sessions yet. Start recording to automatically track your work!</p>
            )}
          </div>

          {/* Auto-fill Status */}
          <div className="autofill-status mb-6">
            <h4 className="autofill-title">Auto-fill Status</h4>
            <div className="autofill-info">
              <FileText className="w-4 h-4" />
              <span>Sessions Auto-filled: {autoFilledSessions.length}</span>
            </div>
            {autoFilledSessions.length > 0 && (
              <div className="recent-autofills">
                <div className="autofill-item">
                  Last auto-fill: {new Date(autoFilledSessions[autoFilledSessions.length - 1]?.timestamp || '').toLocaleString()}
                </div>
              </div>
            )}
          </div>

          {/* Daily Summary (existing functionality) */}
          <div className="daily-summary">
            <div className="text-center mb-4">
              <div className="text-4xl mb-2">{moodEmojis[dailySummary.mood]}</div>
              <h4 className="text-xl font-semibold capitalize mb-2">{dailySummary.mood} Day</h4>
              <div className="flex items-center justify-center gap-2 mb-2">
                <Star className="w-4 h-4 text-yellow-500" />
                <span className="text-lg font-bold">{dailySummary.score}% Focus Score</span>
              </div>
            </div>

            {dailySummary.keyStats.length > 0 && (
              <div className="daily-highlights">
                <h5 className="font-semibold flex items-center gap-2 mb-2">
                  <TrendingUp className="w-4 h-4" />
                  Today's Highlights
                </h5>
                <ul className="highlights-list">
                  {dailySummary.keyStats.map((stat: string, index: number) => (
                    <li key={index} className="highlight-item">
                      <div className="highlight-dot" />
                      {stat}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default Scribe; 